### ISSUE TITLE
Connect to Docker workstation

### ISSUE THREAD

**Issue by aboimpinto** [aboimpinto/NeoLocalDashboard#4]
To connect to the Docker Workstation, the user should be able to  configure the "connection string":
* Operating system (windows / linux)
* Address of the workstation. By default is set to localhost.
- [ ] Docker access provider #5
- [ ] Webform where the docker connection string is defined under Docker setting page #6
- [ ] Card on the Dashboard showing the connection status to the docker workstation #7
